version: 0.2

phases:
  install:
    commands:
      # echo "installing Node 12...."
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      #install dependencies
      - npm install
  build:
    commands:
      #build
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build


Git remote add origin https://github.com/bwitkowski/cloud-for-developers.git
Git push -u origin master